name: CI - test clean utility

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out the repository

      - name: Run clean  # Subtask name
        run: make

      - name: Upload Clean
        uses: actions/upload-artifact@v4
        with:
            name: Clean
            path: ./clean
      
      - name: run clean
        run: ./clean >cleaned_wbcd.txt

      - name: Upload Test Results  # Subtask name
        uses: actions/upload-artifact@v4  # This is an upload task
        with:
          name: Test Results  # Artifact name
          path: ./cleaned_wbcd.txt  # Path to the test results file

